create index commitments_area_owner_idx on public.commitments (area_id, user_id);
create index daily_plan_items_plan_owner_idx on public.daily_plan_items (daily_plan_id, user_id);
create index daily_plan_items_task_owner_idx on public.daily_plan_items (task_id, user_id);
create index daily_plan_items_priority_owner_idx on public.daily_plan_items (priority_id, user_id);
create index daily_plan_items_routine_owner_idx on public.daily_plan_items (routine_occurrence_id, user_id);
create index daily_plan_items_owner_idx on public.daily_plan_items (user_id);
create index goals_area_owner_idx on public.goals (area_id, user_id);
create index priorities_area_owner_idx on public.priorities (area_id, user_id);
create index priorities_goal_owner_idx on public.priorities (goal_id, user_id);
create index priorities_project_owner_idx on public.priorities (project_id, user_id);
create index progress_entries_goal_owner_idx on public.progress_entries (goal_id, user_id);
create index progress_entries_project_owner_idx on public.progress_entries (project_id, user_id);
create index projects_area_owner_idx on public.projects (area_id, user_id);
create index projects_goal_owner_idx on public.projects (goal_id, user_id);
create index routine_occurrences_routine_owner_idx on public.routine_occurrences (routine_id, user_id);
create index routines_area_owner_idx on public.routines (area_id, user_id);
create index task_events_task_owner_idx on public.task_events (task_id, user_id);
create index task_events_owner_idx on public.task_events (user_id);
create index tasks_area_owner_idx on public.tasks (area_id, user_id);
create index tasks_goal_owner_idx on public.tasks (goal_id, user_id);
create index tasks_project_owner_idx on public.tasks (project_id, user_id);
create index tasks_priority_owner_idx on public.tasks (priority_id, user_id);
